#!/bin/bash

jupyter labextension install @jupyter-widgets/jupyterlab-manager
jupyter labextension install @jupyterlab/plotly-extension
jupyter labextension install @jupyterlab/latex
jupyter serverextension enable --sys-prefix jupyterlab_latex