#!/bin/bash

jupyter labextension install @jupyter-widgets/jupyterlab-manager --no-build
jupyter labextension install @jupyterlab/latex --no-build
jupyter serverextension enable --sys-prefix jupyterlab_latex --no-build
jupyter labextension install @jupyterlab/plotly-extension --no-build
jupyter lab build